In [1]:
import pandas as pd
import json

## Plos

In [4]:
plos_train = pd.read_json('../plos/train.json')
plos_val = pd.read_json('../plos/val.json')
plos_test = pd.read_json('../plos/test.json')

print("Plos training obs, ", plos_train.shape[0])
print("Plos val obs, ", plos_val.shape[0])
print("Plos test obs, ", plos_val.shape[0])

Plos training obs,  24773
Plos val obs,  1376
Plos test obs,  1376

In [8]:
plos_train.head()

,id,year,title,sections,headings,abstract,summary,keywords,toc
0,journal.pgen.0030189,2007,The cdx Genes and Retinoic Acid Control the Po...,[[The kidney eliminates metabolic waste in the...,"[Introduction, Results, Discussion, Materials ...","[Kidney function depends on the nephron , whic...","[In the kidney , structures known as nephrons ...","[developmental biology, danio (zebrafish), ver...",NaN
1,journal.ppat.1006076,2016,Using a Novel Partitivirus in Pseudogymnoascus...,[[Pseudogymnoascus destructans ( Pd; previousl...,"[Introduction, Results, Discussion, Materials ...",[White-nose syndrome is one of the most lethal...,[Many species of bats in North America have be...,"[sequencing techniques, fungal spores, vertebr...",NaN
2,journal.pntd.0007498,2019,"The Shan people’s health beliefs, knowledge an...",[[Dengue fever ( DF ) is a mosquito-borne dise...,"[Introduction, Methods, Results, Discussion]",[Sustainable dengue intervention requires the ...,[The burden of dengue has been increasing over...,"[invertebrates, medicine and health sciences, ...",NaN
3,journal.pgen.1001012,2010,Multi-Variant Pathway Association Analysis Rev...,[[Estrogen exposure is critical for the develo...,"[Introduction, Results, Discussion, Materials ...",[Despite the central role of estrogen exposure...,[Estrogen exposure is the most important risk ...,"[oncology/breast cancer, oncology/gynecologica...",NaN
4,journal.pntd.0000605,2010,Expression and Function of Macrophage Migratio...,[[Macrophage migration inhibitory factor ( MIF...,"[Introduction, Methods, Results, Discussion]",[Macrophage migration inhibitory factor ( MIF ...,[Melioidosis is a severe tropical infection ca...,[immunology/cellular microbiology and pathogen...,NaN

In [19]:
def count_words_in_sections(section_lists):
    flat_text = ' '.join([sentence for sublist in section_lists for sentence in sublist])
    return len(flat_text.split())
plos_train['section_word_count'] = plos_train['sections'].apply(count_words_in_sections)
plos_train['summary_word_count'] = plos_train['summary'].astype(str).str.split().str.len()
print("Plos average article length: ", plos_train['section_word_count'].mean())
print("Plos average summary length: ", plos_train['summary_word_count'].mean())

Plos average article length:  6485.9901102006215
Plos average summary length:  194.89593509062286

## eLife

In [6]:
elife_train = pd.read_json('../elife/train.json')
elife_val = pd.read_json('../elife/val.json')
elife_test = pd.read_json('../elife/test.json')

print("elife training obs, ", elife_train.shape[0])
print("elife val obs, ", elife_val.shape[0])
print("elife test obs, ", elife_val.shape[0])

elife training obs,  4346
elife val obs,  241
elife test obs,  241

In [7]:
elife_train.head()

,id,year,title,sections,headings,abstract,summary,keywords
0,elife-35500-v1,2018,National and regional seasonal dynamics of all...,[[It is well-established that death rates vary...,"[Introduction, Results, Discussion, Materials ...","[In temperate climates , winter deaths exceed ...","[In the USA , more deaths happen in the winter...",[epidemiology and global health]
1,elife-48378-v2,2019,Complement and CD4+ T cells drive context-spec...,[[Dysregulated complement activation is increa...,"[Introduction, Results, Discussion, Materials ...",[Whether complement dysregulation directly con...,[Most people have likely experienced the disco...,"[microbiology and infectious disease, immunolo..."
2,elife-04494-v1,2015,Phenotypic complementation of genetic immunode...,"[[HOIL-1 ( encoded by the RBCK1 gene ) , HOIP ...","[Introduction, Results, Discussion, Materials ...",[Variation in the presentation of hereditary i...,[The immune system protects an individual from...,"[microbiology and infectious disease, immunolo..."
3,elife-12352-v2,2016,Cascade of neural processing orchestrates cogn...,[[Flexible control of cognitive processes is f...,"[Introduction, Results, Discussion, Materials ...",[Rapid and flexible interpretation of conflict...,[The brain adapts to control our behavior in d...,[neuroscience]
4,elife-05413-v2,2015,Structural dynamics of myosin 5 during process...,[[Myosin 5a moves in a hand-over-hand fashion ...,"[Introduction, Results, Discussion, Materials ...",[Myosin 5a is a dual-headed molecular motor th...,[Cells use motor proteins that to move organel...,[structural biology and molecular biophysics]

In [21]:
def count_words_in_sections(section_lists):
    flat_text = ' '.join([sentence for sublist in section_lists for sentence in sublist])
    return len(flat_text.split())
elife_train['section_word_count'] = elife_train['sections'].apply(count_words_in_sections)
elife_train['summary_word_count'] = elife_train['summary'].astype(str).str.split().str.len()
print("elife average article length: ", elife_train['section_word_count'].mean())
print("elife average summary length: ", elife_train['summary_word_count'].mean())

elife average article length:  10033.954670961804
elife average summary length:  382.2662218131615